"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Check, CheckCircle2, Download, FileText, Loader2 } from "lucide-react";
import { createChecklistEnquiry } from "@/lib/course";

/**
 * Same-origin asset generated by scripts/generate-checklist-pdf.mjs.
 * Re-run that script to regenerate the PDF after editing its content.
 */
const CHECKLIST_URL = "/downloads/cscs-exam-checklist.pdf";
const CHECKLIST_FILE_NAME = "KINETIKA-CSCS-Exam-Prep-Checklist.pdf";

const WHATS_INSIDE = [
  "Exam facts & format, decoded",
  "A 4-phase preparation plan",
  "All 26 curriculum chapters as tick-boxes",
  "Timed practice & mock-exam strategy",
  "Final week & exam-day tactics",
];

export function ChecklistEnquiryForm() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [challenge, setChallenge] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const validate = (): string | null => {
    if (name.trim().length < 2) return "Please enter your full name.";
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) {
      return "Please enter a valid email address.";
    }
    if (challenge.trim().length > 1000) {
      return "Please keep your answer under 1,000 characters.";
    }
    return null;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    const validationError = validate();
    if (validationError) {
      setError(validationError);
      return;
    }
    setIsLoading(true);
    try {
      await createChecklistEnquiry({ name, email, phone, challenge });
      setSubmitted(true);
    } catch (err) {
      console.error("Checklist enquiry failed:", err);
      setError("Something went wrong while saving your details. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto bg-white rounded-[2.5rem] shadow-xl border border-slate-100 overflow-hidden grid md:grid-cols-2">
      {/* Pitch panel */}
      <div className="bg-slate-900 text-white p-10 md:p-12 flex flex-col justify-center">
        <span className="inline-block w-fit px-3 py-1 rounded-full bg-primary/20 border border-primary/40 text-primary text-xs font-bold uppercase tracking-wider mb-6">
          Free 5-Page PDF
        </span>
        <h2 className="text-2xl font-extrabold mb-6">What&apos;s inside the checklist</h2>
        <ul className="space-y-4 mb-8">
          {WHATS_INSIDE.map((item) => (
            <li key={item} className="flex items-start gap-3">
              <span className="mt-0.5 flex-shrink-0 h-5 w-5 rounded-full bg-primary/20 flex items-center justify-center">
                <Check className="h-3 w-3 text-primary" />
              </span>
              <span className="text-slate-300 text-sm leading-relaxed">{item}</span>
            </li>
          ))}
        </ul>
        <div className="flex items-center gap-3 pt-6 border-t border-white/10">
          <FileText className="h-5 w-5 text-primary flex-shrink-0" />
          <p className="text-sm text-slate-400">Print it or keep it on your device.</p>
        </div>
      </div>

      {/* Form / success panel */}
      <div className="p-10 md:p-12">
        {submitted ? (
          <div className="h-full flex flex-col items-center justify-center text-center py-6">
            <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-full bg-green-100">
              <CheckCircle2 className="h-8 w-8 text-green-600" />
            </div>
            <h3 className="text-2xl font-bold text-slate-900 mb-2">
              You&apos;re all set{name.trim() ? `, ${name.trim().split(/\s+/)[0]}` : ""}!
            </h3>
            <p className="text-slate-600 mb-8">
              Your checklist is ready. Grab it below - happy studying!
            </p>
            <Button
              asChild
              size="lg"
              className="h-14 px-10 text-lg font-bold rounded-full shadow-lg shadow-primary/20"
            >
              <a href={CHECKLIST_URL} download={CHECKLIST_FILE_NAME}>
                <Download className="mr-2 h-5 w-5" />
                Download Your Free Checklist
              </a>
            </Button>
            <p className="mt-6 text-sm text-slate-500">
              Download not starting? Right-click the button and choose &quot;Save link as&quot;.
            </p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} noValidate>
            <h3 className="text-2xl font-bold text-slate-900 mb-1">Get instant access</h3>
            <p className="text-slate-500 text-sm mb-8">
              Fill in the form and the download unlocks right away.
            </p>

            <div className="space-y-5">
              <div className="space-y-2">
                <Label htmlFor="checklist-name">Full name</Label>
                <Input
                  id="checklist-name"
                  type="text"
                  placeholder="e.g. Priya Sharma"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  maxLength={120}
                  disabled={isLoading}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="checklist-email">Email address</Label>
                <Input
                  id="checklist-email"
                  type="email"
                  placeholder="you@example.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  maxLength={200}
                  disabled={isLoading}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="checklist-phone">
                  Phone / WhatsApp <span className="text-slate-400 font-normal">(optional)</span>
                </Label>
                <Input
                  id="checklist-phone"
                  type="tel"
                  placeholder="+91 98765 43210"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  maxLength={30}
                  disabled={isLoading}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="checklist-challenge">
                  What&apos;s your biggest CSCS prep challenge?{" "}
                  <span className="text-slate-400 font-normal">(optional)</span>
                </Label>
                <Textarea
                  id="checklist-challenge"
                  placeholder="e.g. Balancing study with a full-time coaching job..."
                  value={challenge}
                  onChange={(e) => setChallenge(e.target.value)}
                  maxLength={1000}
                  rows={3}
                  disabled={isLoading}
                />
              </div>

              {error ? (
                <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-xl px-4 py-3">
                  {error}
                </p>
              ) : null}

              <Button
                type="submit"
                className="w-full h-14 rounded-2xl text-lg font-bold"
                disabled={isLoading}
              >
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Unlocking your checklist...
                  </>
                ) : (
                  <>
                    <Download className="mr-2 h-5 w-5" />
                    Get My Free Checklist
                  </>
                )}
              </Button>

              <p className="text-xs text-slate-400 text-center leading-relaxed">
                We&apos;ll only use your details to share study tips. See our{" "}
                <Link href="/privacy-policy" className="underline hover:text-slate-600">
                  Privacy Policy
                </Link>
                .
              </p>
            </div>
          </form>
        )}
      </div>
    </div>
  );
}
